security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            oauth:
                failure_path: /connect
                login_path: /connect
                check_path: /connect
                provider: fos_userbundle
                resource_owners:
                    facebook: "/login/check-facebook"
                    google:   "/login/check-google"
                oauth_user_provider:
                    service: my_user_provider
            logout:       true
            anonymous:    true
        secure_area:
            pattern: ^/
            oauth:
                failure_path: /connect
                login_path: /connect
                check_path: /connect
                provider: fos_userbundle
                resource_owners:
                    facebook: "/login/check-facebook"
                    google:   "/login/check-google"
                oauth_user_provider:
                    service: my_user_provider
            anonymous: true
            logout:
                path: /logout
                target: /connect #where to go after logout

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }

