security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        secure_area:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path:     /login
            oauth:
                failure_path: /login
                login_path: /login
                check_path: /login
                provider: fos_userbundle
                resource_owners:
                    facebook: "/login/check-facebook"
                    google:   "/login/check-google"
                oauth_user_provider:
                    service: my_user_provider
            anonymous: true
            logout:
                path: /logout
                target: / #where to go after logout
        login:
            pattern: ^/login$
            security: false

            remember_me:
                key: "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
    acl:
        connection: default
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ideia, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/video, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ed/, role: ROLE_ADMIN }
        - { path: ^/connect, roles: IS_AUTHENTICATED_ANONYMOUSLY }

