site_homepage:
    pattern:  /
    defaults: { _controller: SiteBundle:Default:index }
site_criadores:
    pattern:  /criadores
    defaults: { _controller: SiteBundle:Default:criadores }
site_empresas:
    pattern:  /marcas
    defaults: { _controller: SiteBundle:Default:empresas }
site_comofunciona:
    pattern:  /como-funciona
    defaults: { _controller: SiteBundle:Default:comofunciona }
projetos:
    pattern:  /projetos
    defaults: { _controller: SiteBundle:Project:index }
projetos_new:
    pattern:  /novo/projeto
    defaults: { _controller: SiteBundle:Project:new }
projetos_create:
    pattern:  /criar/projeto
    defaults: { _controller: SiteBundle:Project:create }
projetos_show:
    pattern:  /projeto/{id}
    defaults: { _controller: SiteBundle:Project:show }
projetos_show_2:
    pattern:  /projeto/{id}/{aba}
    defaults: { _controller: SiteBundle:Project:show }
    requirements:
        aba : premiados|forum
projetos_delete:
    pattern:  /ed/projetos/delete/{id}
    defaults: { _controller: SiteBundle:Project:delete }
projetos_edit:
    pattern:  /editar/projeto/{id}
    defaults: { _controller: SiteBundle:Project:edit }
projetos_update:
    pattern:  /atualizar/projeto/{id}
    defaults: { _controller: SiteBundle:Project:update }
site_contato:
    pattern:  /contato
    defaults: { _controller: SiteBundle:Default:contato }
marca:
    pattern:  /ed/marcas
    defaults: { _controller: SiteBundle:Company:index }
marca_new:
    pattern:  /ed/marcas/novo
    defaults: { _controller: SiteBundle:Company:new }
marca_create:
    pattern:  /ed/marcas/criar
    defaults: { _controller: SiteBundle:Company:create }
marca_edit:
    pattern:  /ed/marcas/editar/{id}
    defaults: { _controller: SiteBundle:Company:edit }
marca_update:
    pattern:  /ed/marcas/atualizar/{id}
    defaults: { _controller: SiteBundle:Company:update }
marca_show:
    pattern:  /ed/marcas/detalhe/{id}
    defaults: { _controller: SiteBundle:Company:show }
marca_delete:
    pattern:  /ed/marcas/excluir/{id}
    defaults: { _controller: SiteBundle:Company:delete }
ideia:
    pattern:  /ed/ideias
    defaults: { _controller: SiteBundle:Idea:index }
ideia_new:
    pattern:  /ideia/nova/{id}
    defaults: { _controller: SiteBundle:Idea:new }
ideia_create:
    pattern:  /ideia/criar
    defaults: { _controller: SiteBundle:Idea:create }
ideia_edit:
    pattern:  /ed/ideia/editar/{id}
    defaults: { _controller: SiteBundle:Idea:edit }
ideia_update:
    pattern:  /ed/ideia/atualizar/{id}
    defaults: { _controller: SiteBundle:Idea:update }
ideia_show:
    pattern:  /ed/ideia/detalhe/{id}
    defaults: { _controller: SiteBundle:Idea:show }
ideia_delete:
    pattern:  /ed/ideia/excluir/{id}
    defaults: { _controller: SiteBundle:Idea:delete }
video:
    pattern:  /ed/videos
    defaults: { _controller: SiteBundle:Video:index }
video_new:
    pattern:  /video/novo/{id}
    defaults: { _controller: SiteBundle:Video:new }
video_create:
    pattern:  /video/criar
    defaults: { _controller: SiteBundle:Video:create }
video_edit:
    pattern:  /ed/video/editar/{id}
    defaults: { _controller: SiteBundle:Video:edit }
video_update:
    pattern:  /ed/video/atualizar/{id}
    defaults: { _controller: SiteBundle:Video:update }
video_show:
    pattern:  /ed/video/detalhe/{id}
    defaults: { _controller: SiteBundle:Video:show }
video_delete:
    pattern:  /ed/video/excluir/{id}
    defaults: { _controller: SiteBundle:Video:delete }
premiacao_ideia:
    pattern:  /premiacao/ideia
    defaults: { _controller: SiteBundle:IdeaPrize:index }
premiacao_ideia_new:
    pattern:  /premiacao/ideia/nova/{id}
    defaults: { _controller: SiteBundle:IdeaPrize:new }
premiacao_ideia_create:
    pattern:  /premiacao/ideia/criar
    defaults: { _controller: SiteBundle:IdeaPrize:create }
premiacao_ideia_edit:
    pattern:  /premiacao/ideia/editar/{id}
    defaults: { _controller: SiteBundle:IdeaPrize:edit }
premiacao_ideia_update:
    pattern:  /premiacao/ideia/atualizar/{id}
    defaults: { _controller: SiteBundle:IdeaPrize:update }
premiacao_ideia_show:
    pattern:  /premiacao/ideia/detalhe/{id}
    defaults: { _controller: SiteBundle:IdeaPrize:show }
premiacao_ideia_delete:
    pattern:  /premiacao/ideia/excluir/{id}
    defaults: { _controller: SiteBundle:IdeaPrize:delete }
premiacao_video:
    pattern:  /premiacao/video
    defaults: { _controller: SiteBundle:VideoPrize:index }
premiacao_video_new:
    pattern:  /premiacao/video/nova/{id}
    defaults: { _controller: SiteBundle:VideoPrize:new }
premiacao_video_create:
    pattern:  /premiacao/video/criar
    defaults: { _controller: SiteBundle:VideoPrize:create }
premiacao_video_edit:
    pattern:  /premiacao/video/editar/{id}
    defaults: { _controller: SiteBundle:VideoPrize:edit }
premiacao_video_update:
    pattern:  /premiacao/video/atualizar/{id}
    defaults: { _controller: SiteBundle:VideoPrize:update }
premiacao_video_show:
    pattern:  /premiacao/video/detalhe/{id}
    defaults: { _controller: SiteBundle:VideoPrize:show }
premiacao_video_delete:
    pattern:  /premiacao/video/excluir/{id}
    defaults: { _controller: SiteBundle:VideoPrize:delete }
