parameters:
    my_user_provider.class: Clube\SiteBundle\Security\Core\User\FOSUBUserProvider
#    site.example.class: Clube\SiteBundle\Example

services:
    site.registration.form.type:
        class: Clube\SiteBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: site_user_registration }
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id}]
    clube.twig.site_extension:
        class: Clube\SiteBundle\Twig\SiteExtension
        tags:
            - { name: twig.extension }
    site.form.type.suggest:
        class: Clube\SiteBundle\Form\Type\SuggestType
        arguments: ["@doctrine.orm.entity_manager", "@form.type_guesser.doctrine"]
        tags:
            -  { name: form.type, alias: entity_hidden }
#    site.example:
#        class: %site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
